Config                   = {}
Config.Lang              = 'en' 
Config.ForceSteam        = true    
Config.MultiServerSync   = true  
Config.EnableDiscordLink = true 
Config.webhookban        = "TAVS WEBHOOK"
Config.webhookunban      = "TAVS WEBHOOK"
Config.TextEn = {
	start         = "Ban Sistēma Tika Veiksmīgi Ielādēta!",
	starterror    = "KĻŪDA Ban Sistēma Tika Neveiksmīgi Ielādēta!",
	banlistloaded = "Ban Saraksts Ieladēts",
	historyloaded = "Ban Vecais Saraksts Ielādēts.",
	loaderror     = "KĻŪDA Ban Sarakstus Nesanāca Ielādēt",
	cmdban        = "/sqlban (ID) (Skaits Dienās) (Iemēsls)",
	cmdbanoff     = "/sqlbanoffline (ID) (Skaits Dienās) (Steam Vārds)",
	cmdhistory    = "/sqlbanhistory (Steam VāRDS) or /sqlbanhistory 1,2,2,4......",
	forcontinu    = " dienas. Lai turpinātu uzraksti /sqlreason [reason]",
	noreason      = "Iemēsls nav aprakstīts.",
	during        = " laikā: ",
	noresult      = "Rezultāti nav atrasti.",
	isban         = " tika banots",
	isunban       = " tika unbanots",
	invalidsteam  = "Hey, steam ir nepieciešams lai spēlētu mūsu serverī!.",
	invalidid     = "Spēlētāja ID Nav Atrasts",
	invalidname   = "Vārds nav atrasts",
	invalidtime   = "Nepareizs Ban Daudzums",
	alreadyban    = " tika jau banots par : ",
	yourban       = "Tu tiki banots no servera par: ",
	yourpermban   = "Tu tiki permantly banots no servera par: ",
	youban        = "Tu esi banots no servera par: ",
	forr          = " dienas. Par: ",
	permban       = " permanently par: ",
	timeleft      = ". Laiks Atlicis: ",
	toomanyresult = "Kļūda.",
	day           = " dienas ",
	hour          = " stundas ",
	minute        = " minūtes ",
	by            = "no",
	ban           = "Banot Spēlētāju",
	banoff        = "Banot Offline Spēlētāju",
	dayhelp       = "Daudzums (dienās) bans",
	reason        = "Iemēsls",
	history       = "Parāda visus iepriekšējos banus",
	reload        = "Pārlādē Ban Sarakstu.",
	unban         = "Unbanot Spēlētāju.",
	steamname     = "Steam Vārds"
}
